# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/x/textdetect

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/x/textdetect

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/x/textdetect/CMakeFiles /home/x/textdetect/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/x/textdetect/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mser

# Build rule for target.
mser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mser
.PHONY : mser

# fast build rule for target.
mser/fast:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/build
.PHONY : mser/fast

#=============================================================================
# Target rules for targets named textdetect

# Build rule for target.
textdetect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 textdetect
.PHONY : textdetect

# fast build rule for target.
textdetect/fast:
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/build
.PHONY : textdetect/fast

afterline.o: afterline.cpp.o
.PHONY : afterline.o

# target to build an object file
afterline.cpp.o:
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/afterline.cpp.o
.PHONY : afterline.cpp.o

afterline.i: afterline.cpp.i
.PHONY : afterline.i

# target to preprocess a source file
afterline.cpp.i:
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/afterline.cpp.i
.PHONY : afterline.cpp.i

afterline.s: afterline.cpp.s
.PHONY : afterline.s

# target to generate assembly for a file
afterline.cpp.s:
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/afterline.cpp.s
.PHONY : afterline.cpp.s

extend.o: extend.cpp.o
.PHONY : extend.o

# target to build an object file
extend.cpp.o:
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/extend.cpp.o
.PHONY : extend.cpp.o

extend.i: extend.cpp.i
.PHONY : extend.i

# target to preprocess a source file
extend.cpp.i:
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/extend.cpp.i
.PHONY : extend.cpp.i

extend.s: extend.cpp.s
.PHONY : extend.s

# target to generate assembly for a file
extend.cpp.s:
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/extend.cpp.s
.PHONY : extend.cpp.s

fast_clustering.o: fast_clustering.cpp.o
.PHONY : fast_clustering.o

# target to build an object file
fast_clustering.cpp.o:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/fast_clustering.cpp.o
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/fast_clustering.cpp.o
.PHONY : fast_clustering.cpp.o

fast_clustering.i: fast_clustering.cpp.i
.PHONY : fast_clustering.i

# target to preprocess a source file
fast_clustering.cpp.i:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/fast_clustering.cpp.i
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/fast_clustering.cpp.i
.PHONY : fast_clustering.cpp.i

fast_clustering.s: fast_clustering.cpp.s
.PHONY : fast_clustering.s

# target to generate assembly for a file
fast_clustering.cpp.s:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/fast_clustering.cpp.s
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/fast_clustering.cpp.s
.PHONY : fast_clustering.cpp.s

group_classifier.o: group_classifier.cpp.o
.PHONY : group_classifier.o

# target to build an object file
group_classifier.cpp.o:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/group_classifier.cpp.o
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/group_classifier.cpp.o
.PHONY : group_classifier.cpp.o

group_classifier.i: group_classifier.cpp.i
.PHONY : group_classifier.i

# target to preprocess a source file
group_classifier.cpp.i:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/group_classifier.cpp.i
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/group_classifier.cpp.i
.PHONY : group_classifier.cpp.i

group_classifier.s: group_classifier.cpp.s
.PHONY : group_classifier.s

# target to generate assembly for a file
group_classifier.cpp.s:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/group_classifier.cpp.s
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/group_classifier.cpp.s
.PHONY : group_classifier.cpp.s

max_meaningful_clustering.o: max_meaningful_clustering.cpp.o
.PHONY : max_meaningful_clustering.o

# target to build an object file
max_meaningful_clustering.cpp.o:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/max_meaningful_clustering.cpp.o
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/max_meaningful_clustering.cpp.o
.PHONY : max_meaningful_clustering.cpp.o

max_meaningful_clustering.i: max_meaningful_clustering.cpp.i
.PHONY : max_meaningful_clustering.i

# target to preprocess a source file
max_meaningful_clustering.cpp.i:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/max_meaningful_clustering.cpp.i
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/max_meaningful_clustering.cpp.i
.PHONY : max_meaningful_clustering.cpp.i

max_meaningful_clustering.s: max_meaningful_clustering.cpp.s
.PHONY : max_meaningful_clustering.s

# target to generate assembly for a file
max_meaningful_clustering.cpp.s:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/max_meaningful_clustering.cpp.s
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/max_meaningful_clustering.cpp.s
.PHONY : max_meaningful_clustering.cpp.s

min_bounding_box.o: min_bounding_box.cpp.o
.PHONY : min_bounding_box.o

# target to build an object file
min_bounding_box.cpp.o:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/min_bounding_box.cpp.o
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/min_bounding_box.cpp.o
.PHONY : min_bounding_box.cpp.o

min_bounding_box.i: min_bounding_box.cpp.i
.PHONY : min_bounding_box.i

# target to preprocess a source file
min_bounding_box.cpp.i:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/min_bounding_box.cpp.i
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/min_bounding_box.cpp.i
.PHONY : min_bounding_box.cpp.i

min_bounding_box.s: min_bounding_box.cpp.s
.PHONY : min_bounding_box.s

# target to generate assembly for a file
min_bounding_box.cpp.s:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/min_bounding_box.cpp.s
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/min_bounding_box.cpp.s
.PHONY : min_bounding_box.cpp.s

mser.o: mser.cpp.o
.PHONY : mser.o

# target to build an object file
mser.cpp.o:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/mser.cpp.o
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/mser.cpp.o
.PHONY : mser.cpp.o

mser.i: mser.cpp.i
.PHONY : mser.i

# target to preprocess a source file
mser.cpp.i:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/mser.cpp.i
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/mser.cpp.i
.PHONY : mser.cpp.i

mser.s: mser.cpp.s
.PHONY : mser.s

# target to generate assembly for a file
mser.cpp.s:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/mser.cpp.s
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/mser.cpp.s
.PHONY : mser.cpp.s

nfa.o: nfa.cpp.o
.PHONY : nfa.o

# target to build an object file
nfa.cpp.o:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/nfa.cpp.o
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/nfa.cpp.o
.PHONY : nfa.cpp.o

nfa.i: nfa.cpp.i
.PHONY : nfa.i

# target to preprocess a source file
nfa.cpp.i:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/nfa.cpp.i
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/nfa.cpp.i
.PHONY : nfa.cpp.i

nfa.s: nfa.cpp.s
.PHONY : nfa.s

# target to generate assembly for a file
nfa.cpp.s:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/nfa.cpp.s
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/nfa.cpp.s
.PHONY : nfa.cpp.s

region.o: region.cpp.o
.PHONY : region.o

# target to build an object file
region.cpp.o:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/region.cpp.o
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/region.cpp.o
.PHONY : region.cpp.o

region.i: region.cpp.i
.PHONY : region.i

# target to preprocess a source file
region.cpp.i:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/region.cpp.i
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/region.cpp.i
.PHONY : region.cpp.i

region.s: region.cpp.s
.PHONY : region.s

# target to generate assembly for a file
region.cpp.s:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/region.cpp.s
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/region.cpp.s
.PHONY : region.cpp.s

region_classifier.o: region_classifier.cpp.o
.PHONY : region_classifier.o

# target to build an object file
region_classifier.cpp.o:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/region_classifier.cpp.o
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/region_classifier.cpp.o
.PHONY : region_classifier.cpp.o

region_classifier.i: region_classifier.cpp.i
.PHONY : region_classifier.i

# target to preprocess a source file
region_classifier.cpp.i:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/region_classifier.cpp.i
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/region_classifier.cpp.i
.PHONY : region_classifier.cpp.i

region_classifier.s: region_classifier.cpp.s
.PHONY : region_classifier.s

# target to generate assembly for a file
region_classifier.cpp.s:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/region_classifier.cpp.s
	$(MAKE) -f CMakeFiles/textdetect.dir/build.make CMakeFiles/textdetect.dir/region_classifier.cpp.s
.PHONY : region_classifier.cpp.s

test_mser.o: test_mser.cpp.o
.PHONY : test_mser.o

# target to build an object file
test_mser.cpp.o:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/test_mser.cpp.o
.PHONY : test_mser.cpp.o

test_mser.i: test_mser.cpp.i
.PHONY : test_mser.i

# target to preprocess a source file
test_mser.cpp.i:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/test_mser.cpp.i
.PHONY : test_mser.cpp.i

test_mser.s: test_mser.cpp.s
.PHONY : test_mser.s

# target to generate assembly for a file
test_mser.cpp.s:
	$(MAKE) -f CMakeFiles/mser.dir/build.make CMakeFiles/mser.dir/test_mser.cpp.s
.PHONY : test_mser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mser"
	@echo "... rebuild_cache"
	@echo "... textdetect"
	@echo "... afterline.o"
	@echo "... afterline.i"
	@echo "... afterline.s"
	@echo "... extend.o"
	@echo "... extend.i"
	@echo "... extend.s"
	@echo "... fast_clustering.o"
	@echo "... fast_clustering.i"
	@echo "... fast_clustering.s"
	@echo "... group_classifier.o"
	@echo "... group_classifier.i"
	@echo "... group_classifier.s"
	@echo "... max_meaningful_clustering.o"
	@echo "... max_meaningful_clustering.i"
	@echo "... max_meaningful_clustering.s"
	@echo "... min_bounding_box.o"
	@echo "... min_bounding_box.i"
	@echo "... min_bounding_box.s"
	@echo "... mser.o"
	@echo "... mser.i"
	@echo "... mser.s"
	@echo "... nfa.o"
	@echo "... nfa.i"
	@echo "... nfa.s"
	@echo "... region.o"
	@echo "... region.i"
	@echo "... region.s"
	@echo "... region_classifier.o"
	@echo "... region_classifier.i"
	@echo "... region_classifier.s"
	@echo "... test_mser.o"
	@echo "... test_mser.i"
	@echo "... test_mser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

